### ISSUE TITLE
v1.0.7 Firmware header invalid 

### ISSUE THREAD

**Issue by RonaldCrb** [Foundation-Devices/passport-firmware#60]
## summary
trying to upgrade the firmware from my device from `v1.0.6` to `v1.0.7` using the recommended sdcard method, with the `.bin` file downloaded from the official setup guide

## expected behavior
the device will upgrade its firmware from `v1.0.6` to `v1.0.7` and reboot

## actual behavior
after selecting the `.bin` file, the device shows the message: `Firmware header is invalid. The selected firmware header is invalid and cannot be installed`

**Comment by coreylakey** [comment]
Hi Ronald,

Thanks for raising the issue with us. Are you able to check the sha256 of the `v1.0.7` binary file you're attempting to upgrade with?

It should match the sha256 posted in the release notes. In the case of `v1.0.7` it would be `265716676ca91bd724ad48b28a6877841b216003b7b03bbfd6e5eee85a5c057a`.

To do this on Linux, you can use the command:
`shasum -b -a 256 passport-fw-1.0.7.bin`

Also, we've seen issues with some primary devices copying the file to the SD card causing issues. What was the primary device you used to copy the `v1.0.7` binary to the SD card?

**Comment by RonaldCrb** [comment]
this is the output of the suggested command
```sh
265716676ca91bd724ad48b28a6877841b216003b7b03bbfd6e5eee85a5c057a *passport-fw-1.0.7.bin
```
the primary device is lenovo ideapad running Ubuntu Desktop 20.04

**Comment by coreylakey** [comment]
Can you try the same binary on a different microSD?

Also, did you update from `v1.0.0` to `v1.0.6` and then `v1.0.7`? Were there any other updates in between?

**Comment by RonaldCrb** [comment]
the first time i set it up after i bought it was 1.0.5... then i upgraded to 1.0.6, now im trying 1.0.7. 

ive tried with the original 8gb Sandisk Industrial XI microsd  and with an 128Mb delkin industrial microsd. both resulted in the same issue.

**Comment by coreylakey** [comment]
Are you checking the binary `shasum` while on the microSD? I am curious if your microSD is changing it in some way. Can you check it while on the microSD and off of the microSD?

**Comment by jonathancross** [comment]
Seems this can be closed?

**Comment by jeandudey** [comment]
Thanks @jonathancross for bringing this topic again!

Just for reference, in case anyone encounters an issue like this in the future:

- The official firmware update guides:
  -  https://docs.foundationdevices.com/setup-guide#step-5-update-firmware
  - https://docs.foundationdevices.com/en/firmware-update
- Verify the downloaded firmware:
  - https://docs.foundationdevices.com/en/firmware-update#verifying-the-firmware
- Make sure that the format of the MicroSD is FAT32

And for developers or advanced users that want to check if it's an issue with the Passport device or the Micro SD card, the firmware header can be dumped to see if it's valid directly from the Micro SD card:

```
# Build the cosign tool. Requires Docker and Just.
just cosign-tool
# Dump firmware header
./cosign -f /<path-to-microsd>/passport-fw-1.0.8.bin -x
FW header content:
	timestamp: 1640764131
	   fwdate: Dec 28, 2021
	fwversion: 1.0.8
	 fwlength: 1211852
	      key: 0
	signature: b546c58b60539b49ae6d51ba22b717771714a214749166a379cdfad6c213e2c3e9d81a20c47b986c8afb39d0716e9681ce2575eeec0eab44b9eb02020e7d9fda
	      key: 1
	signature: bd479ac5500adb55384c2d418d5c4037b8fda6c64b195ada67c797d1d39ae7b303d8a0d0044c4be7cd0986ace75cf76812ed7e5d21eb9c563eba39a6fed3e903

FW Build Hash:    ad6b4f5f4ae0b7e05ec35415713ea1ff7dde3edf10870876b1c8bd07391419d1
FW Download Hash: 6c6d1531685ac91eeea202d1fb818c4930a208a7590ab36e118bf5eb91e29e83
```

`FW Download Hash` should match the one published in the [releases page] for that file, and the hash performed with `shasum -b 256`, and the [verification in the passport](https://docs.foundationdevices.com/en/firmware-update#firmware-contents-verification-on-passport).

[releases page]: https://github.com/Foundation-Devices/passport-firmware/releases/

---

@RonaldCrb I will close the issue, feel free to reach and/or reopen to us if the problem persists.
