### ISSUE TITLE
Use ur:crypto-account to pair with Sparrow Wallet

### ISSUE THREAD

**Issue by craigraw** [Foundation-Devices/passport-firmware#65]
I'd like to motivate for Passport to implement [ur:crypto-account](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-015-account.md) for pairing with Sparrow Wallet. Desktop cameras can be poor in quality, and minimizing data is one way to improve UX when scanning QRs.

Keystone uses `ur:crypto-account`, and exports a single sig wallet with a single (non-animated) QR code. It must be noted they are only exporting a single script type, but exporting a custom selection of script types (for example all single sig script types) is supported.

The difference in CBOR bytes between Passport and Keystone is over 10x: Passport is 1840 bytes versus Keystone at 139 bytes. Even including the other single sig script types, I think the QR export would be much more manageable using the compact format of crypto-account.

No changes to Sparrow Wallet are required, and the current and previous versions will happily accept `ur:crypto-account` for pairing if the Passport supplies it.

**Comment by zachherbert** [comment]
Thanks Craig! The crpyto-account format is on our short term roadmap and we will get it implemented. But we do want to make sure to support multiple script types for the best possible UX. 

We will take a closer look and see if we can be sending this data more efficiently, both by switching to crypto-account format and also potentially sending fewer script types.

**Comment by craigraw** [comment]
@zachherbert just to let you know that Wolf McNally of Blockchain Commons is implementing `ur:crypto-account` into his software, and we have agreed to make a few changes to the format to correct some technical issues he found in the formatting. The issues are detailed here: https://github.com/BlockchainCommons/Research/pull/99, and relate to CBOR tagging and adding a new "cosigner" function to partial output descriptors for multisig keys.

The good news is that Sparrow will continue to read the old crypto-account format (along with the new one) without any problems. 

Wolf is also now a coauthor on this spec, and it has now been thoroughly reviewed by him, so this is good progress on it gaining further acceptance.

**Comment by zachherbert** [comment]
Thanks @craigraw. @FoundationKen please take note.
