### ISSUE TITLE
New Foundation logo splash screen

### ISSUE THREAD

**Issue by eupn** [Foundation-Devices/passport-firmware#77]
After upgrading to the latest (`v1.0.8`) version of firmware I've noticed that it still has an older Foundation logo.

Wanted to try and update the logo myself by using SVG logo from the Press Kit and building a firmware with the new logo, but was warned by Ken that loading a modified firmware into the device could potentially brick it.

So instead of making a PR I figured that I could just share the new splash screen here.

![image](https://user-images.githubusercontent.com/36292692/149448476-3f9d6559-9242-4083-ab18-ffec6e3d04dd.png)

Since the newer logo uses gradients and will be grayscale if converted to black-and-white, the logo variant above uses Positioned dithering to convert grayscale into 1-bit pixels w/ some minor tweaks to brightness/contrast to allow for a decent looking dithered gradient.

Another option is to ignore the grayscale and use a plain simple black-and-white variant:

![image](https://user-images.githubusercontent.com/36292692/149448884-62ee31eb-613e-4594-b683-935a47c50c02.png)

**Comment by FoundationKen** [comment]
Thanks for this!  We'll get the new logo into the Batch 2 Passports!
