### ISSUE TITLE
Bitcoin Core pairing bug

### ISSUE THREAD

**Issue by iamthen0nce** [Foundation-Devices/passport-firmware#91]
During pairing with Bitcoin Core, the user is meant to scan the first receiving address that is shown through 'Request payment'.
Unfortunately, the Bitcoin Core QR code contains the address as uppercase which Passport doesn't understand.
This is the one bit that isn't shown in the video (https://youtu.be/HAsDeHWOAko?t=246), just described, so I assume it was on someone's todo list and just never completed.

Would appreciate timely fix!

**Comment by BitcoinQnA** [comment]
@iamthen0nce this was [fixed](https://github.com/Foundation-Devices/passport-firmware/releases/tag/v1.0.8) in 1.0.8. I presume you are running out of date firmware. 

Could you update and confirm everything is working ok?

**Comment by iamthen0nce** [comment]
> @iamthen0nce this was [fixed](https://github.com/Foundation-Devices/passport-firmware/releases/tag/v1.0.8) in 1.0.8. I presume you are running out of date firmware.
> 
> Could you update and confirm everything is working ok?

It's on 1.0.9. Just tried again. I create a new receiving address in Bitcoin-QT (not sure how to get a QR code through bitcoin-cli directly) and select 'Verify address' on the Passport. It fails because the QR code is all uppercase.

**Comment by BitcoinQnA** [comment]
Interesting, perhaps Core has updated their formatting since our last fix. Can you confirm which version Bitcoin QT you're running? Also are you able to share the QR code? 

Understand if you'd prefer not to. I can do some testing my end but it will take me a little longer to come back to you.

**Comment by iamthen0nce** [comment]
> EDIT - Ignore above request, I have replicated the issue. We'll have a fix in next release.
> 
> CC @FoundationKen
Great, thanks a lot! Apparently you need a `.lowercase()` somewhere else, too... ;) 

> Interesting, perhaps Core has updated their formatting since our last fix. Can you confirm which version Bitcoin QT you're running? 
FWIW, this is on v23.0, Qt version 5.15.2

**Comment by iamthen0nce** [comment]
By the way, there is no way to debug something like this in an emulator, is it?
I think it would be really helpful if e.g. when trying a fix for such a bug, you don't need to upload a developer key to your personal hardware wallet and flash it.

**Comment by BitcoinQnA** [comment]
Will have to let @FoundationKen comment on your question, but it should be possible yes.

Issue has now been fixed in [v1.1.0](https://github.com/Foundation-Devices/passport-firmware/releases/tag/v1.1.0), thank you for the report.
